version: 1.0.{build}
image: Visual Studio 2019 Preview
configuration: Debug
platform: Any CPU
environment:
  DeployExtension: false
before_build:
  - nuget restore
build:
  verbosity: minimal
artifacts:
- path: deploy\Vsix
  name: Nav.Language.Extension
- path: deploy\Build Tools
  name: Nav.Language.BuildTools