version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
build:
  verbosity: minimal
artifacts:
- path: Nav.Language.Extension\bin\Debug\Pharmatechnik.Nav.Language.Extension.2017.vsix
  name: Nav.Language.Extension
