version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
environment:
  DeployExtension: false
build:
  verbosity: minimal
artifacts:
- path: deploy\Vsix
  name: Nav.Language.Extension
- path: deploy\Build Tools
  name: Nav.Language.BuildTools