

$versioningScripts=Join-Path $PSScriptRoot Versioning.ps1

. $versioningScripts


$dir = Join-Path $PSScriptRoot "..\Nav.Language.Tests\Regression\Tests"

$customBuildFile = Join-Path $PSScriptRoot "..\Nav.Language.Tests\CustomBuild.targets"

$header=@'
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Version: $version
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
'@

$version='*.*.*'

$headerMatch=$ExecutionContext.InvokeCommand.ExpandString($header)
Write-Host $headerMatch

$version=ReadVersion $customBuildFile

$headerReplacement=$ExecutionContext.InvokeCommand.ExpandString($header)
Write-Host $headerReplacement


ls $dir -recurse -Filter '*.expected.cs'  | Edit-File -Pattern $headerMatch -Replacement $headerReplacement -SimpleMatch
