//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nav.Language.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nav.Language.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [namespaceprefix NS.1]
        ///
        ///[using U1]
        ///[using U2]
        ///
        ///taskref &quot;F1&quot;;
        ///taskref &quot;F2&quot;;
        ///
        ///taskref TR1 [namespaceprefix NS.2]		
        ///		    [notimplemented]	
        ///		    [result RT1 r1]
        ///{
        ///    init I1 [abstractmethod] [params T1 param1, T2&lt;T3, T4&lt;T5&gt;&gt; param2] do &quot;D1&quot;;
        ///    exit E1;       
        ///	end;
        ///}
        ///// Comment before task T1
        ///task T1 [code &quot;code1&quot;] 
        ///		[base B0: B1, B2]
        ///		[generateto &quot;g1&quot;]
        ///		[params P1 p1, P2 p2]
        ///		[result R1 r1]
        ///{
        ///	// Node Declaration (init, exit, end sind bereits in der obigen TaskDeclaration vollst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllRules {
            get {
                return ResourceManager.GetString("AllRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [namespaceprefix Pharmatechnik.Apotheke.XTplus.Artikelstamm.ArtikelBearbeiten]
        ///[using System]
        ///[using System.Collections.Generic]
        ///[using Pharmatechnik.Apotheke.XTplus.Common.IWFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Common.WFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.Core.IBOL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.Core.IWFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.Core.WFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Common.IBOL]
        ///[using Pharmatechnik.Apotheke.XTplus.Artikelstamm.IB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LargeNav {
            get {
                return ResourceManager.GetString("LargeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [namespaceprefix Pharmatechnik.Apotheke.XTplus.Verkauf]
        ///[using System.Collections.Generic]
        ///[using Pharmatechnik.Apotheke.XTplus.Common.IWFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Common.WFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.NavigationEngine.IWFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.NavigationEngine.WFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.Core.IWFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.Core.WFL]
        ///[using Pharmatechnik.Apotheke.XTplus.Framework.Util.Exceptio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NavWithError {
            get {
                return ResourceManager.GetString("NavWithError", resourceCulture);
            }
        }
    }
}
